### ISSUE TITLE
水浒传

### ISSUE THREAD

**Issue by zerone0x** [zerone0x/TempLog#2]
记录一些剧情感想

**Comment by zerone0x** [comment]
4
解决偷菜问题：
打贼
理解贼为什么偷菜
第一个就没法解决，反而把问题变严重。第二个就可以。

**Comment by zerone0x** [comment]
陆谦背叛林冲，可真不是义啊。没想到客套的人真不靠谱

**Comment by zerone0x** [comment]
6
林冲心真好，但好心给好人啊。对坏人给好心，反而被利用

**Comment by xissshawww** [comment]
顶一顶

**Comment by zerone0x** [comment]
7
陆谦终于死了。现在看很多东西还是不理解。原著里的林冲没有这么软。最烦这种迎合观众的导演编剧

**Comment by zerone0x** [comment]
再就是剧情反映当时朝廷多么腐败啊

**Comment by zerone0x** [comment]
高俅他儿子这种人能活着真靠烂嘴皮

**Comment by zerone0x** [comment]
后会有期 多保重！

**Comment by zerone0x** [comment]
9 
杨志这送玉进狱喝酒，我也感到悲凉了。

**Comment by zerone0x** [comment]
官府命官杀人前还奉承 牛逼啊。真是面前说好话，背后捅刀子。

**Comment by zerone0x** [comment]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/39543393/150379033-cdcaba9a-585c-4b83-bc64-6634c76c870a.png">

**Comment by zerone0x** [comment]
12
一级压一级，都奉承。恶俗

**Comment by zerone0x** [comment]
很多时候人们说宿命论就是扯淡，比如你去运生辰纲，那得考虑很多客观因素，防止被偷，路途劳累。假如说“该偷的早晚偷”，这就是逃避现实。不是宿命，是鸵鸟心态。

**Comment by zerone0x** [comment]
13
林冲杀王伦 爽极。宋江灵活如水，心胸开阔。而且善于用人（当然后面不知会不会被坑）。看七个兄弟在一起可真的开心。肝胆相照，义气

**Comment by zerone0x** [comment]
14
看张文远这口气，我有点忍不住笑。自己对自己没点数。

**Comment by zerone0x** [comment]
婆媳这脑回路简直了…我目瞪口呆

**Comment by zerone0x** [comment]
宋江用钱笼络人心

**Comment by zerone0x** [comment]
每次走下坡都是被最亲近的人坑
orz

**Comment by zerone0x** [comment]
雷都头和宋江太nb了 会说话

**Comment by zerone0x** [comment]
雷公 谁不给自己留条后路
宋江 哈哈哈 不能下棋 走 喝酒去！

**Comment by zerone0x** [comment]
看潘金莲这有点理解不了，为何冒犯武松底线

**Comment by zerone0x** [comment]
20
醉打蒋门神 爽快
19 
孙二娘也爽快

**Comment by zerone0x** [comment]
古代社会把人性搞的淋漓尽致。比如对你好，奖赏你，离你亲近，可能最后是这个人害死你。再比如，有人想要处死你，还会对你奉承，说给你个好差事，但实际上是去送死。想要不死，不能相信武力值低于自己的任何人，再就是必须武力值够高。再就是流放了赶紧溜，比如鲁智深

**Comment by zerone0x** [comment]
武松相关剧情有槽点，张官人挖人-对他好-赏佩丫鬟，明显是坑，可武松还是知恩图报。但没辙，看剧都是上帝视角，我要是武松，也是乖乖领赏。

**Comment by zerone0x** [comment]
25

宋江是个矛盾的人。上梁山并不痛快，不像林冲那样接受现实。还是想回去当官的。

24

大家一起救宋江真热闹

**Comment by zerone0x** [comment]
27 
前面看的战太菜了 祝家庄这有意思

**Comment by zerone0x** [comment]
28
宋江不当头领自是为了后日取头领性命啊。假如他同意当了统领，那必日后没这么威严。

**Comment by zerone0x** [comment]
32
宋江让卢做统领 无非是因为名声比较正气 而不是真心给权力

**Comment by zerone0x** [comment]
37

木船看起来再宏伟，材质的防御也不行

**Comment by zerone0x** [comment]
38

宋江和高俅有啥区别？嘴上说着为兄弟，内心不都是想着自己的前途

**Comment by zerone0x** [comment]
39

到最后林教头就鲁智深这一个朋友，悲从中来

**Comment by zerone0x** [comment]
43

梁山兄弟凑在一起是自由 各得其所。这共同目的变成功名，可就变味了

**Comment by zerone0x** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/39543393/151529072-116ff9b9-5ebe-4855-afc4-7daaeeaba1f2.png">

**Comment by zerone0x** [comment]
睡前开始想电视剧水浒传时间线

林冲是刚开始的第一个讨论最多的悲剧英雄。
鲁智深-情节很happy，还能顺便让人反思什么是自然。自发性。
林冲上梁山-七星偷生辰纲-杨志送玉被贬送生辰纲。
宋江帮晁-晁上梁山-杨志上青龙山
晁变梁山老大
宋江杀婆媳被贬-和武松在柴家相遇
武松打虎见哥哥-潘金莲爱而不得-武松走了-哥哥被害
武松被贬-贬后被陷害-黑化-上青龙山
晁救宋江。热闹
主线来了。
宋江打祝家庄，还打了一个什么来着，得到很多英雄。
晁义气报仇反而中毒死去。
宋变老大，梁山目标-招安。
第一个问题-梁山没名气-逼卢上山。
再找太尉什么见皇上。
和朝廷保持博弈，打一会，客气一会。
招安后。
宋江兄弟们杀江南。
兄弟们生死难还。
结束。

水浒传有趣的是人细节，电视剧有趣的是打打杀杀和场景。
